/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class PemesananView extends javax.swing.JFrame {

    /**
     * Creates new form PemesananView
     */
    private Pemesanan pemesanan;
    
    public PemesananView() {
        initComponents();
        
        pemesanan = new Pemesanan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelNama = new javax.swing.JLabel();
        textNama = new javax.swing.JTextField();
        labelJumlah = new javax.swing.JLabel();
        textJumlah = new javax.swing.JTextField();
        labelAlamat = new javax.swing.JLabel();
        textAlamat = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        tombolPesan = new javax.swing.JButton();
        tombolReset = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        labelStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel1.setLayout(new java.awt.GridLayout(3, 2, 10, 10));

        labelNama.setText("Nama Pembeli");
        jPanel1.add(labelNama);
        jPanel1.add(textNama);

        labelJumlah.setText("Jumlah Barang");
        jPanel1.add(labelJumlah);

        textJumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textJumlahKeyTyped(evt);
            }
        });
        jPanel1.add(textJumlah);

        labelAlamat.setText("Alamat Pengiriman");
        jPanel1.add(labelAlamat);

        textAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAlamatActionPerformed(evt);
            }
        });
        jPanel1.add(textAlamat);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        tombolPesan.setText("Pesan");
        tombolPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolPesanActionPerformed(evt);
            }
        });
        jPanel4.add(tombolPesan);

        tombolReset.setText("Reset");
        tombolReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombolResetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tombolResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tombolResetMouseExited(evt);
            }
        });
        jPanel4.add(tombolReset);

        jPanel2.add(jPanel4);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        labelStatus.setText("Status: Menunggu Input");
        jPanel3.add(labelStatus);

        jPanel2.add(jPanel3);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolPesanActionPerformed
        // TODO add your handling code here:
        pemesanan.setNamaPembeli(textNama.getText());
        pemesanan.setJumlahBarang(Integer.parseInt(textJumlah.getText()) );
        pemesanan.setAlamatPengiriman(textAlamat.getText());
        
        try
        {
            if(pemesanan.getNamaPembeli().isEmpty() || pemesanan.getAlamatPengiriman().isEmpty() )
            {
                labelStatus.setText("Status: Nama dan Alamat harus diisi!");
            } 
            else if (pemesanan.getJumlahBarang() <= 0)
            {
                labelStatus.setText("Status: Jumlah barang harus diisi lebih dari 0!");
            }
            else 
            {
                labelStatus.setText("Status: Pemesanan berhasi!");
                JOptionPane.showMessageDialog(this,
                        "Pemesanan Atas Nama "+pemesanan.getNamaPembeli()+" Berhasil Dilakukan!", 
                        "Pemberitahuan Pemesanan",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch (NumberFormatException e)
        {
            labelStatus.setText("Jumlah barang harus berupa angka!");
        }
        
    }//GEN-LAST:event_tombolPesanActionPerformed

    private void textAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAlamatActionPerformed

    private void tombolResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolResetMouseClicked
        // TODO add your handling code here:
        textNama.setText("");
        textJumlah.setText("");
        textAlamat.setText("");
        labelStatus.setText("Status: Form di-reset!");
    }//GEN-LAST:event_tombolResetMouseClicked

    private void tombolResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolResetMouseEntered
        // TODO add your handling code here:
        labelStatus.setText("Status: Klik tombol reset untuk mengosongkan form.");
    }//GEN-LAST:event_tombolResetMouseEntered

    private void tombolResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolResetMouseExited
        // TODO add your handling code here:
        labelStatus.setText("Status: Menunggu input...");
    }//GEN-LAST:event_tombolResetMouseExited

    private void textJumlahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textJumlahKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != KeyEvent.VK_BACK_SPACE)
        {
//            batalkan input selain angka
            evt.consume(); 
            labelStatus.setText("Status: Input hanya boleh berupa angka.");
        }
    }//GEN-LAST:event_textJumlahKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PemesananView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PemesananView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PemesananView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PemesananView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PemesananView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelAlamat;
    private javax.swing.JLabel labelJumlah;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JTextField textAlamat;
    private javax.swing.JTextField textJumlah;
    private javax.swing.JTextField textNama;
    private javax.swing.JButton tombolPesan;
    private javax.swing.JButton tombolReset;
    // End of variables declaration//GEN-END:variables
}
